### ISSUE TITLE
tfe_workspace_ids name regex support in the data source

### ISSUE THREAD

**Issue by daftkid** [hashicorp/terraform-provider-tfe#1050]
#### Use-cases
I have a bunch of TFC workspaces that follow the naming convention: `<prefix>_<account_name>_<aws_region>_<layer_name>`.
For example, `cn_sandbox-1_cn-north-1_vpc`.

#### Attempted Solutions
Here I want to get all workspaces that start from my particular prefix and are related to the target region. I do not care about account and layer names.
I need to use an asterisk not only as a prefix or suffix but also in the middle of the string, please see the example. 
```
data "tfe_workspace_ids" "regional" {
  for_each     = toset(var.target_regions)
  names        = ["${local.name_prefix}_*_${each.value}_*"]
  organization = data.tfe_organization.org.name
}
```
Running this example, I've got zero list of IDs.

I know that I can use `setintersection` TF function but that is not an ideal approach.

#### Proposal
Have the logic for using `regex` in the WS name (somewhere here https://github.com/hashicorp/terraform-provider-tfe/blob/main/internal/provider/data_source_workspace_ids.go#L56)

**Comment by barrettclark** [comment]
Regex searching is something that we approach with extreme caution. You've got a lot of different pieces of information embedded in your workspace names. We recommend utilizing tags to capture the pieces of information so that it's more easily searchable.

Would something like this work for you:

```
data "tfe_workspace_ids" "regional" {
  organization = tfe_organization.org.name
  tag_names    = [var.target_environment, var.target_aws_region]
}
output "regional" {
  value = data.tfe_workspace_ids.regional.full_names
}
```
The tags are additive in the `tag_names` filter, so that would give you all workspaces that have both required tags. I added the output to print it out so you could see it after running an apply.
