### ISSUE TITLE
Import statement not working but CLI does

### ISSUE THREAD

**Issue by nikolay** [hashicorp/terraform-provider-tfe#1077]
#### Terraform Cloud/Enterprise version

Terraform Cloud

#### Terraform version

```plaintext
1.5.7
```

#### Terraform Configuration Files

```terraform
import {
  id = "<org>/<email>/owners"
  to = tfe_team_organization_member.owners["<email>"]
}
```

#### Debug Output

```plaintext
$ terraform plan
Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/<REDACTED>/terraform-cloud/runs/<REDACTED>

Waiting for the plan to start...

Terraform v1.5.7
on linux_amd64
Initializing plugins and modules...
tfe_organization.default: Refreshing state... [id=<REDACTED>]
tfe_workspace.terraform_cloud: Refreshing state... [id=<REDACTED>]
╷
│ Error: Cannot import to non-existent resource address
│
│ Importing to resource address
│ tfe_team_organization_member.owners["<email>"] is not possible,
│ because that address does not exist in configuration. Please ensure that
│ the resource key is correct, or remove this import block.
╵
Operation failed: failed running terraform plan (exit 1)
$ terraform import 'tfe_team_organization_member.owners["<email>"]' '<org>/<email>/owners'

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

$ terraform plan
Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/<REDACTED>/terraform-cloud/runs/<REDACTED>

Waiting for the plan to start...

Terraform v1.5.7
on linux_amd64
Initializing plugins and modules...
tfe_organization.default: Refreshing state... [id=<REDACTED>]
tfe_workspace.terraform_cloud: Refreshing state... [id=<REDACTED>]
╷
│ Error: error retrieving user with email <email> from organization <org>: resource not found
│
│
╵
Operation failed: failed running terraform plan (exit 1)
$ terraform import 'tfe_organization_membership.members["<email>"]' '<org>/<email>'

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

$ terraform show 'tfe_organization_membership.members["<email>"]'
╷
│ Error: Failed to read the given file as a state or plan file
│
│ State read error: Error loading statefile: open tfe_organization_membership.members["<email>"]: no such file or directory
│
│ Plan read error: open tfe_organization_membership.members["<email>"]: no such file or directory
╵
❯ terraform state list
tfe_organization_membership.members["<email>"]
tfe_team_organization_member.owners["<email>"]
```

#### Expected Behavior

The `import` statement should work just like the CLI does.

#### Actual Behavior

The `import` fails. A strange error appears after successfully importing via the CLI without being associated with a specific resource. Not only does the email exist in that organization, but that's the owner. In addition, the last `import` followed by `show` says that the object does not exist (it actually talks about files!), yet it does after calling `terraform state list`.

**Comment by sebasslash** [comment]
Hi Nikolay 👋  That's because the differences between the two are nuanced. `terraform import` will modify Terraform state directly, without any plannable output. The idea behind `import` blocks was to able to leverage plannable behavior. An `import` block acts like an intent to change your Terraform state, but won't unless you `terraform apply`. This is identical to any resource in Terraform. If you specify a resource address that does not exist in state nor in your configuration, the Terraform plan will fail. 

- Import using the CLI command and mangle your Terraform configuration to match what was imported in state (The old way and non-trivial for `cloud` backend users).
- Use `import` blocks if using remote state, and ensure your resource addresses are defined in state:
```hcl
import {
  id = "<org>/<email>/owners"
  to = tfe_team_organization_member.owners["<email>"]
}

resource "tfe_team_organization_member" "owners" {
  for_each = <my-set-of-emails>
} 
```
Both options require you to ensure your configuration matches what was in state. This is still tedious so check out [Automatically Generating Import Configuration](https://developer.hashicorp.com/terraform/language/import/generating-configuration) (EXPERIMENTAL!). This is not foolproof as the Terraform plugin protocol is not aware of odd resource schema behaviors, i.e mutually exclusive attributes, custom validation, etc since these are features of the provider SDK. Make sure you consult with the TFE provider docs if you run into errors applying. 

I'm going to go ahead and close this issue since this isn't specific to the TFE provider & more so general Terraform behavior. Thanks!
