### ISSUE TITLE
tfe_workspace failing - Resource not found

### ISSUE THREAD

**Issue by jim-mclean** [hashicorp/terraform-provider-tfe#1325]
#### Terraform Cloud/Enterprise version

Terraform Cloud

#### Terraform version

```plaintext
1.8.1
```

#### Terraform Configuration Files

```terraform
import {
  to = tfe_organization.this
  id = var.tfc_org_name
}
resource "tfe_organization" "this" {
  name = var.tfc_org_name
  email                    = "xxx@mycompany.com"
  session_timeout_minutes  = 20160
  session_remember_minutes = 20160
  collaborator_auth_policy = "password"
  cost_estimation_enabled                                 = true
  send_passing_statuses_for_untriggered_speculative_plans = false
  aggregated_commit_status_enabled                        = false
  assessments_enforced                                    = true
  allow_force_delete_workspaces                           = true
}
```

#### Debug Output

Plan log:  https://gist.github.com/jim-mclean/8f783e0c3d9109da05a4038a8a2e3c75

Apply log:  https://gist.github.com/jim-mclean/aa0f5cc9331d3ca0a26a0fe207c4de88

```plaintext
2024-04-20T18:44:58.189Z [ERROR] vertex "tfe_organization.this" error: Error updating organization REDACTED: resource not found
```

#### Expected Behavior
tfe_organization deployment should have succeed post import

#### Actual Behavior
Apply failed

#### Additional Context
Importing existing organization and associated resources.  Plan succeeds, but tfe_organization apply fails.

**Comment by brandonc** [comment]
@jim-mclean Hi, and thanks for opening the issue. I'm fairly sure that this issue has something to do with the authentication credentials that the tfe provider is using. 404 (resource not found) is returned by the API when a user does not have authorization to perform the action so that the API does not leak information about the existence of resources.

Please double check that the configured credentials have access to manage the org settings. If running this within TFC/TFE, you can set a TFE_TOKEN environment variable because the run environment is fairly constrained in terms of the built-in authentication that the tfe provider picks up. Let me know if this doesn't fix your issue!

**Comment by jim-mclean** [comment]
@brandonc wouldn't the Org Token have enough privileges for tfe_organization?  If not, what permissions are needed?

FYI, I am also using tfe_organization_settings in the same run and do t have any issues with that.

**Comment by brandonc** [comment]
@jim-mclean You would think that from the name! But no! Please see [this table](https://developer.hashicorp.com/terraform/cloud-docs/users-teams-organizations/api-tokens#access-levels) for more information about the organization access token. In short, the org access token can't create or manage an organization but can be used for some initial setup before delegating further access using team tokens.

**Comment by brandonc** [comment]
@jim-mclean I'm unsure of the details of the organziation_settings resource you are managing, but perhaps it has not needed to update the organization so far? If you find that it can, I can investigate further.

**Comment by jim-mclean** [comment]
Thanks @brandonc !!!  This solved our problem.
