### ISSUE TITLE
Attach sentinel policy per workspace

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-tfe#139]
Hi,

Would be great if we are able to attach a policy set to workspace instead of attach workspace to policy set; example:

resource "tfe_workspace_sentinel_attach" "this" {
 policy_set_id = ""
 workspace_id = ""
}

Thanks

**Comment by etopeter** [comment]
Can you elaborate how this is going to be used? What individual attachments allow you to do that policy resource with list of workspaces aren't. 

Today you can attach policy to workspaces like this: 
```
resource "tfe_policy_set" "foo" {
  name = "foo"
  organization = org_id
  workspace_external_ids = [...]
}```
One thing to look out for is the fact that policy can be global so attributes global and workspace_external_ids are mutually exclusive.

**Comment by chrisarcand** [comment]
The current schema reflects the actual TFC/E API utilized, and I don't believe this resource would add any additional value beyond what the API is today. There exists no case, presently, where someone who _doesn't_ configure the policy set can opt-in to it being enforced on a workspace.

In any case, closing as the original poster's account has since been deleted and discussion can't continue anyway.
