### ISSUE TITLE
tfe_oauth_client support for other VCS

### ISSUE THREAD

**Issue by ausfestivus** [hashicorp/terraform-provider-tfe#213]
Evening,

I understand that the tfe_oauth_client does not support Bitbucket or Azure DevOps currently. (ref: https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/oauth_client)

Im guessing that that is because the functionality doesn't exist in the upstream VCS to allow the resource to support those platforms.

If that is correct, can we have this issue left open (if there isn't another issue already) to track a request to each unsupported platform vendor to introduce the functionality in their platforms to allow the tfe_oauth_client to work with their platforms?

**Comment by brandonc** [comment]
Hello! It's been awhile, but since this issue was opened, oauth_client has added support for bitbucket, azure devops, and a few other VCS providers.

**Comment by ausfestivus** [comment]
Hey @brandonc just took a look at the provider doco. It states that Azure DevOps Services are not supported.
Im assuming this is closed because the support for Azure DevOps Server is now available.

Question: since Azure DevOps Services is still not yet supported, can this be reopened?

**Comment by brandonc** [comment]
@ausfestivus Hello! So unfortunately for providers that require an OAuth Application style browser flow, like Devops Services, Bitbucket Cloud, etc. the Terraform Cloud API (and therefore this provider) can't support that because of the specific limitations of OAuth. I actually just [commented here ](https://github.com/hashicorp/terraform-provider-tfe/issues/96#issuecomment-1362164238) on a similar issue.

Perhaps I can ask someone to expand our documentation to explain this limitation better than I can.

**Comment by ausfestivus** [comment]
Yea, thanks @brandonc, understood.
