### ISSUE TITLE
tfe_variable does not recognize environment variables

### ISSUE THREAD

**Issue by derekschauland** [hashicorp/terraform-provider-tfe#235]
When trying to build out a terraform cloud workspace, I would love to get the environment variables added as well. But I receive the message : Error - no value for required variable.

I have a variable defined for arm_client_id for use with Azure and it is set in TF_VAR_arm_client_id environment variable on my system, however terraform plan does not pick this up.

The backend configuration does add the workspace, but no environment variables are added. An example of the resource block for this is below:

resource "tfe_variable" "arm_client_id" {
    key                                             = "ARM_CLIENT_ID"
    value                                           = var.arm_client_id
    category                                        = "env"
    sensitive                                       = true
    workspace_id                                    = tfe_workspace.workspace.id
    description                                     = "ARM_CLIENT_ID"
}

not sure what / if anything I am missing

**Comment by chrisarcand** [comment]
Hello! Can you provide a bit more information about how you are trying to apply your configuration?

* Are you using the [remote backend](https://www.terraform.io/docs/backends/types/remote.html), or executing Terraform on your local machine?
* If you are using the remote backend, are you attempting to provision variables to the workspace that you've configured your backend for?

If so, it could be that your environment variable isn't found because the remote backend is attempting to find variables in your Terraform Cloud workspace, not your local environment. [See Variables in CLI-driven Runs for more info.](https://www.terraform.io/docs/cloud/run/cli.html#variables-in-cli-driven-runs)

Does that help?

**Comment by derekschauland** [comment]
I was trying to provision variables into terraform cloud. Ill check out the linked docs - thanks

**Comment by chrisarcand** [comment]
@derekschauland Any update on this? Should this issue be closed?

**Comment by derekschauland** [comment]
I think I have what I need - please close this issue

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
