### ISSUE TITLE
support cli driven workspace creation vs vcs

### ISSUE THREAD

**Issue by Stromweld** [hashicorp/terraform-provider-tfe#248]
TFE supports VCS, CLI, and API driven workspaces. This provider defaults to VCS and doesn't support the other options. My request is to add support for creating the other types of workspaces.

**Comment by chrisarcand** [comment]
Hi!

Terraform Cloud/Enterprise workspaces don't have a particular 'type' - in other words, the workspaces you create with this provider can be configured and used with any of the three workflows you mention above: [UI/VCS-driven](https://www.terraform.io/docs/cloud/run/ui.html), [CLI-driven](https://www.terraform.io/docs/cloud/run/cli.html) with the [remote backend](https://www.terraform.io/docs/backends/types/remote.html), or [API-driven](https://www.terraform.io/docs/cloud/run/api.html) for CI/integration systems.

There's no default, either - [configuring a VCS repository on a workspace is optional](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/workspace#vcs_repo). 

Could you explain a bit more what you mean by support for the other options? The reason an API exists to configure a VCS repository (as above) but _not_ anything for initiating runs via CLI or API is because nothing is required to be configured on the workspace at all for those cases.

**Comment by Stromweld** [comment]
I guess it wasn't very clear to me on how to create a CLI driven workspace until you explained it here with the vcs being optional. I was thinking along the lines of how the GUI when creating a workspace first asks which workflow you want and then creates it based on that. Makes sense though if you don't add a vcs then it'd be a CLI or API supported workflow and by adding vcs it becomes vcs driven workflow.

Adding additional info on vcs option or examples of each with example description would help make that more clear to users.
