### ISSUE TITLE
Terraform plan shows non-sensitive tfe_variable as (sensitive value)

### ISSUE THREAD

**Issue by dkirrane** [hashicorp/terraform-provider-tfe#255]
Terraform Plan `~ update in-place` shows a non sensitive `tfe_variable` as `(sensitive value)`

```
------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # tfe_variable.this will be updated in-place
  ~ resource "tfe_variable" "this" {
        category     = "terraform"
        hcl          = false
        id           = "var-123456789"
        key          = "my_config"
        sensitive    = false
      ~ value        = (sensitive value)
        workspace_id = "ws-123456789"
    }
```

**Comment by chrisarcand** [comment]
Hi! [I saw your thread on the HashiCorp Discuss forum and replied there.](https://discuss.hashicorp.com/t/why-does-terraform-plan-output-show-tfe-variable-value-as-sensitive-value/18875/6?u=chrisarcand) Here's the gist of the reply below (with only the provider pertinent parts), for posterity here.

The `tfe_variable.sensitive` argument (set to `false`, above) is related to [Terraform Cloud’s notion of sensitive values](https://www.terraform.io/docs/cloud/workspaces/variables.html#sensitive-values), which is that they should not be retrievable after their initial creation. 

The value is marked as sensitive ([statically, via the schema](https://github.com/hashicorp/terraform-provider-tfe/blob/6e06664a6d9599ab491feb074f85e4cea41784ae/tfe/resource_tfe_variable.go#L43)) because the value is still returned on initial creation and stored in state, and since it may be marked as a sensitive value by the platform, the provider opts to play it safe and avoid any chance of exposing it, given that possibility. 

Thanks!
