### ISSUE TITLE
tfe_variable value update not detected

### ISSUE THREAD

**Issue by anweiss** [hashicorp/terraform-provider-tfe#270]
With the following config:

```tf
variable "myvar" {
  type = string
}

resource "tfe_variable" "myvar" {
  key          = "mykey"
  value        = var.myvar
  category     = "terraform"
  workspace_id = data.tfe_workspace.myworkspace.id
}
```

if the variable already exists, but the value has changed, Terraform is not detecting that the value needs to be updated.

I'm using v0.24.0 of this provider.

**Comment by chrisarcand** [comment]
Hi!

Can you describe what you mean by the value changing? Are you saying that the existing value you provisioned has been manually changed in the TFC/E API and you expect Terraform to detect that drift automatically?

**Comment by anweiss** [comment]
As in, `var.myvar` is being set to a value that is different from the value previously set for the variable in TF Cloud

**Comment by chrisarcand** [comment]
Are you running this configuration in a Terraform Cloud workspace with the [remote backend](https://www.terraform.io/docs/language/settings/backends/remote.html)? How are you supplying the change to that variable? Can you show more of your configuration?

What I suspect is happening is that you are attempting to change the value of the variable in the same workspace you are provisioning with. In this case, the input variable `myvar` will be set with the one from TFC (even when a [variables file is supplied](https://www.terraform.io/docs/cloud/workspaces/variables.html#loading-variables-from-files)), as the workspace is managing your variables. For more information on this, see the [workspace variables documentation](https://www.terraform.io/docs/cloud/workspaces/variables.html). The value for `var.myvar` is unchanged because the variable remains unchanged in the workspace.

There are two paths I'd suggest, in this case:

* If you wish to set variables for the primary workspace in the same configuration that the workspace is using, you don't really need to provision a `tfe_variable`. You can either set the value in the configuration itself or provide a `*.auto.tfvars` file.

* If you wish to utilize the provider here to provision variables, provision them separately from the primary workspace utilizing that variable. It's very common to use a 'bootstrap' or 'meta' workspace to manage Terraform Cloud with this provider independent of the infrastructure you're provisioning with it. In other words, defining a configuration which then manages variables for your workspaces to use. 

Does that help?

**Comment by anweiss** [comment]
Thanks @chrisarcand. Super helpful! Turns out this was an oversight on my end. I was accidentally setting the `tfe_variable.myvar.key` to `myvar`, which is the same as `variable.myvar`, thus a circular config. Closing.

**Comment by chrisarcand** [comment]
That's a _much_ more concise way of saying what I said above, really 😆 Glad it's resolved! 💞
