### ISSUE TITLE
Org Token: Notification configuration creation fails with "Error creating notification configuration my-test-notification-configuration: resource not found"

### ISSUE THREAD

**Issue by jw-maynard** [hashicorp/terraform-provider-tfe#275]
I want to bring attention back to #89. I've sent an email to support about this but hoping and issue here might bring this to the attention of the TFC team better than a comment on the closed issue. 

The org token is described in the support docs as being intended to be used when managing things inside TFC, like the configuration of workspaces. It seems to me to logically follow that it should also be able to manage any configuration of said workspaces including the notification configurations. If there's a good reason for this not to happen that I'm missing please let me know, but to me it seems like a bug that I can manage almost anything about my workspaces except notification with this token.

**Comment by brandonc** [comment]
Hey, sorry no one ever responded to this issue. I believe the platform tries to keep the org token scope focused on initial setup tasks instead of allowing it to manage everything. Notification configuration is seen as more of a team-specific setup. See the [Orgnanization API Tokens](https://developer.hashicorp.com/terraform/cloud-docs/users-teams-organizations/api-tokens#organization-api-tokens) section of the API Token docs for a more nuanced explanation.

Here is the official matrix of token access, which I hope helps determine which token to use!

https://developer.hashicorp.com/terraform/cloud-docs/users-teams-organizations/api-tokens#access-levels

I don't know if it helps, but using separate root modules differentiate initial/team configuration, or using separate, aliased providers with different tokens are two approaches you can use to configure the provider differently.

**Comment by afrazkhan** [comment]
@brandonc, I've tried this with an owner token, and it still gives the error:

```bash
Error creating notification configuration slack: resource not found
```

This is the same error I used to get when using an organisational token for workspace configuration.

**Comment by knanao** [comment]
@afrazkhan 
How do you try to authenticate with TFC?
If you're trying to use `terraform login` or `credentials` block although remote operations, you should use `token` or `TFE_TOKEN` instead.

https://registry.terraform.io/providers/hashicorp/tfe/latest/docs#authentication
