### ISSUE TITLE
tfe_workspace: How to manage itself?

### ISSUE THREAD

**Issue by ldb** [hashicorp/terraform-provider-tfe#291]
I created a module that is supposed to manage a couple of resources using the `remote` backend for terraform, which implicitly created a new workspace. Let's call this `workspace-A`.
I then added another `tfe_workspace` resource to the module which matches the settings of workspace-A, and used the ID of workspace-A to import it.
Now workspace-A contains a state which is linked to workspace-A itself, and workspace-A should be able to manage itself.

However, when I edit any of the attributes of workspace-A, terraform tells me the resource does not exist:
`Error: Error updating workspace ws-<ID of workspace-A>: resource not found`

When I use `terraform state list` and `terraform state show tfe_workspace.workspace_A` I do get the correct ID back, though.

Is it possible for a state to manage a workspace which itself is stored in?

**Comment by chrisarcand** [comment]
The scenario you describe is technically possible, but not generally recommended. There are some bits of 'provisioning a workspace with the workspace itself' that may work but several others that would not, on the basis that what you're trying to change on the workspace first runs within the present state of that same workspace! 😄 Examples: 

* Changing execution mode - switching from one mode to another would require doing a run in the execution mode you don't want to use, first.
* Provisioning variables to the workspace - There would be little utility to them, because you'd have to have them in your configuration anyway.
* etc, etc.

A common pattern for provisioning TFC/E with TFC/E is to use a 'bootstrap' workspace - a workspace who's sole purpose is to provision other workspaces that contain the infrastructure you're managing with TFC. You can also set up [run triggers](https://www.terraform.io/docs/cloud/workspaces/run-triggers.html) to kick off runs on those workspaces when something on your bootstrap workspace changes, if that makes sense.

---

As far as your specific error, if you really would still like to try and use a workspace with itself, a `resource not found` error is commonly because the request is unauthorized. Did you configure a token for the provider?

The remote backend and provider are separate components that do not share authentication, so if you haven't provided a token for the provider to use, you'll receive that message. See [the documentation on Authentication](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs#authentication) for more info.

Hope that helps!

**Comment by ldb** [comment]
> Provisioning variables to the workspace - There would be little utility to them, because you'd have to have them in your configuration anyway.

I imagine that it would be possible to provision such a workspace with variables once and those would be used in subsequent runs, if execution mode "remote" is used. Where am I wrong with this?

> A common pattern for provisioning TFC/E with TFC/E is to use a 'bootstrap' workspace

That makes sense, thank you! It would be great to have all workspaces defined as code though.

Thank you for your input on the authentication. I will keep experimenting with this a bit.

**Comment by chrisarcand** [comment]
> I imagine that it would be possible to provision such a workspace with variables once and those would be used in subsequent runs, if execution mode "remote" is used. Where am I wrong with this?

You aren't wrong! But if you're provisioning a variable on to the workspace itself to be used in the workspace itself, to use that value usefully in the same workspace you might as well use the value you had to provide to `tfe_variable` in the first place rather than pulling it as a workspace variable later 😄 

Coincidentally, I've seen this before and you may find more information/context [in this Discuss thread](https://discuss.hashicorp.com/t/variable-management-with-tfe-variable-requires-to-apply-twice/20298/2?u=chrisarcand) which attempts to do the same thing. 

Cheers!
