### ISSUE TITLE
TFE provider needs to tolerate objects that are changed externally (treat as config drift)

### ISSUE THREAD

**Issue by MasakariDOR** [hashicorp/terraform-provider-tfe#309]
### Terraform Version
```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/tfe v0.24.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- tfe_variable
- tfe_workspace
- others???

### Terraform Configuration Files
```hcl
resource "tfe_workspace" "workspace" {
  name              = "myTest1"
  organization      = "eDev"
  terraform_version = "0.14.7-bundle-1.0.5"
  auto_apply         = true
  working_directory = ""
}

resource "tfe_variable" "terraform_workspace_variables" {
  workspace_id = tfe_workspace.workspace.id
  key          = "myVar"
  value        = "myValue2"
  category     = "env"
}
```

### Debug Output
https://gist.github.com/MasakariDOR/d04b37de2030763fef11ad9dcaf645a7

### Expected Behavior
A workspace variable was already defined. It should have just had it's value set to the one I've defined in my resource.

### Actual Behavior
The TFE provider produced the error `Error: Error creating env variable myVar: invalid attribute

Key has already been taken`
It looks like it didn't search to see if this key was already in use.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a workspace using a tfe_workspace resource
2. `terraform apply`
3. Manually add a variable (as a user might do this themselves)
4. Add a tfe_variable resource to your code with the same name as 3.
5. `terraform apply`

### Important Factoids
In environments where people can create their own workspace variables and the onboarding of user accounts is automated using Terraform with the TFE provider, one user can bring down the automation simply by deleting and recreating a workspace variable!
This doesn't just apply to variables but to other resource types like "workspace" too. If a workspace that was created by Terraform was removed in Terraform Enterprise, it should just be recreated (treated as configuration drift). This probably affects a wide variety of resource types with this provider.

**Comment by chrisarcand** [comment]
Hi!

The intended behavior of Terraform is a provider should return an error if asked to create something that already exists; if you want to bind an existing remote object to an instance in a Terraform configuration as you describe, that's the intent of [`terraform import`](https://www.terraform.io/docs/cli/import/index.html).

Interestingly enough there does exist a small precedent for Terraform provider behavior to behave similarly as you describe, not by automatically importing a resource but by overwriting it. This is sometimes used in cases where a resource represents something akin to a configuration value rather than an infrastructure component. In this provider, tfe_variable has been discussed as a good candidate for this behavior, which you can read all about in #133.

Note that even there, replacement of a resource that already exists would be the opt-in exception, and not the normal expected behavior of Terraform resources. Reviewing all other resources that exist today, I don't believe anything besides `tfe_variable` should allow for that behavior (and again, not by default).

This is all to say, Terraform erroring when attempting to create resources that already exist due to some unique constraint on the resource (like a workspace name in an organization, etc) is expected behavior. For variables specifically, as mentioned in #133 a feature as described there would definitely still be accepted.

Thank you!
