### ISSUE TITLE
Variables in Terraform cloud dont update...

### ISSUE THREAD

**Issue by lexarflash8g** [hashicorp/terraform-provider-tfe#318]
Im creating variables using tfe provider and setting variable like so 

```
resource "tfe_variable" "test" {
  key          = "cluster_name"
  value        = var.cluster_name
  category     = "terraform"
  workspace_id = data.tfe_workspace.tfenv.id
  description  = "a useful description"
  
```
  

 I have a test.auto.tfvars file and set my variables:

cluster_name = "my-cluster"

variables.tf

variable "cluster_name" {
type = string
}

So if I create if on first apply.. it populates in the UI... but when I change the value in the .tfvars file... Terraform doesnt detect the changes ... tf plan/apply shows this 

```
on linux_amd64
Configuring remote state backend...
Initializing Terraform configuration...
tfe_variable.test: Refreshing state... [id=var-oyRMmmu3sfNEcpgt]

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and the remote system(s). As a result, there are no actions to
take.

```

Using Terraform 15.3 with tfe_provider version 

 tfe = {
      version = "~> 0.25.0"
    }

The only way to update the variable is to remove it from state and recreate again.. which isnt ideal.. the documentation says it should allow updates and it should pick up changes from .auto.tfvars file..

**Comment by chrisarcand** [comment]
Hi!

This is working as expected, and isn't related to this provider but the platform itself. Happy to help, though!

Specifying values in `.auto.tfvars` files do not write to the value of the workspace variable in Terraform Cloud (which is what you're provisioning with `tfe_variable` and this provider); the values in remote environment are just overridden for that particular run. In other words, you're provisioning a workspace variable with the provider and then ignoring it by specifying it in the `.auto.tfvars` file.

>  the documentation says it should allow updates and it should pick up changes from .auto.tfvars file

Could you point to where this is? Perhaps we can make this more clear if it seems to imply that it writes values instead of just override. I found [this documentation](https://www.terraform.io/docs/cloud/workspaces/variables.html#loading-variables-from-files) which seems to fit my description above:

> If any automatically loaded variables have the same names as variables specified in the Terraform Cloud workspace, the workspace's values will override the automatic values.


(Closing this as it's not related to the provider and this issue tracker, but happy to continue the conversation on improved documentation!)

**Comment by lexarflash8g** [comment]
Thanks, I used the docs here:
https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/variable

Creates, updates and destroys variables.

Is there a workflow to update the tfe_variable by passing in my values from .tfvars ot *.auto.tfvars ? 
So it will pick up changes from new values...

Because our org currently is manually updating values in the TF Cloud UI and its very tedious..

"You can also use the optional Terraform Cloud Provider to update a workspace's variables. This has the same effect as managing workspace variables manually or via the API, but can be more convenient for large numbers of complex variables."

I can try it using the API.. but that would rather be complicated... another option is perhaps tainting the TFE_VARIABLES and forcing them to recreate in TF cloud? Could that work?

**Comment by chrisarcand** [comment]
If you're just trying to manage the variables for the single workspace you're provisioning with, you don't need to use the provider to set the workspace variables nor tediously update the values in the TFC UI - you can just use your *.auto.tfvars file, and that's it. 

If you're looking to do more complex management and securing of variables within multiple remote workspaces, etc, a common pattern you'll see is the concept of a 'bootstrap' workspace wherein you use a single workspace to provision workspaces and their variables separately using this provider. With the workspace configured via this 'bootstrap' workspace, you then provision whatever real thing you're doing in those configured workspaces.

Although it's theoretically possible to craft configuration to take the value from your auto.tfvars file to provide vlaues for `tfe_variables`, I wouldn't recommend it - It's not practical to manage a workspace's variables within the same configuration for that workspace using `tfe_variable` because at that point you're provisioning the provisioner. You'd need to "apply twice" (once to provision the variables to the workspace, and once to use them, when you could have just used the value you provided `tfe_variable` to wherever you need it in the first place).

**Comment by lexarflash8g** [comment]
Great thanks 

So we can just ditch using tfe_variable and they don't be present in the UI.. I figured it may be helpful if other people are working on the workspace and don't have access to the tfvars values to update them, but then the runs wouldn't be consistent

So I think the option is to either use tfe_variable and that populates them in UI and then manually change them later, or just use auto.tfvars to update values. Latter would be much more preferable for automation such as running ci/cd. Because this issue was a major blocker for say running ci job on GitHub actions or Travis... realize that now both together won't work. So encrypting auto.tfvars in repo, and decrypting for terraform apply will work (UI variables override auto tfvars so those will be deleted)

**Comment by chrisarcand** [comment]
If you need to change the variables per-run in automation, given the current state of things I would look at two options:

* Directly utilizing the [Variables API](https://www.terraform.io/docs/cloud/api/variables.html) to set variables for the workspace in that automation before doing the run.
* Use this provider, but provisioning the variables to the workspace in question via another workspace, first. A 'bootstrap' workspace is a pretty common pattern where one is dedicated to running Terraform to provision TFC itself. You could then kick off a run in the main workspace (either in your CI, via [run triggers](https://www.terraform.io/docs/cloud/workspaces/run-triggers.html), whatever), and get the same effect.
