### ISSUE TITLE
structured-run-output-enabled support

### ISSUE THREAD

**Issue by travisby** [hashicorp/terraform-provider-tfe#327]
Hello,

We were just reading [https://www.hashicorp.com/blog/new-apply-user-interface-for-terraform-cloud](New Apply User Interface for Terraform Cloud) and are really excited to start using the new interface!  Unfortunately it appears that this setting is not yet available.

Enabling it in the UI, I noticed the only difference is that `.data.attributes.structured-run-output-enabled` needs to be true in the POST body.

Not sure if this is intentionally unavailable (since it's a beta/experimental feature) or if this is a legitimate good feature request :)

**Comment by iniinikoski** [comment]
Looking forward to this as well!

Did a quick look, looks like go-tfe does not support this yet (https://github.com/hashicorp/go-tfe) :/

**Comment by jgrumboe** [comment]
So far it's not even mentioned in the official TFE/TFC API https://www.terraform.io/docs/cloud/api/workspaces.html

**Comment by radditude** [comment]
Thanks for raising this issue, I'm glad to see so much interest in this feature!

We generally try to avoid adding documentation and provider support until features are out of beta since API decisions may change before the feature is finalized - we'll definitely be adding support for this as soon as is feasible, though!

**Comment by radditude** [comment]
After some further discussion, we're going to bypass our usual workflow in this case and add provider support while this feature is still marked as beta.

In the event that the feature _does_ get removed (unlikely! but anything's possible), we'll pull it out of the provider and go-tfe without going through a formal deprecation process since it's just the one workspace attribute.

**Comment by smckay-signifyd** [comment]
Thanks for this! Is there a timeline for when #330 will make it to a release?

**Comment by jgrumboe** [comment]
It would still need a docs and CHANGELOG change, right?

**Comment by radditude** [comment]
0.26.0 should be out soon! Thanks for your patience on this.

**Comment by radditude** [comment]
Support for `structured_run_output_enabled` is now live as of [v0.26.0](https://registry.terraform.io/providers/hashicorp/tfe/0.26.0)!
