### ISSUE TITLE
New Resource to create workspace state version and set as current state

### ISSUE THREAD

**Issue by Sreerag74031** [hashicorp/terraform-provider-tfe#357]
#### Use-cases
We are following the TFCB docs to migrate state from gcs backend to TFCB. However we have many workspaces and would like to automate the state migration as part of workspace creation.
Our plan is to create new workspace,  in lock it (#251),  use google provider to read state file,  create state version  and unlock the workspace. 
Currently we are able to read state file from gcs backend. With the lock/unlock feature and state version feature we would we able to automate state migration.

**Comment by jgrumboe** [comment]
Hmmm...for the usecase you're describing seems like a one-shot task and in my opinion a resource would only make sense if you want to do this migration over and over regularly again - and I bet that's not the intention. 

We also had to migrate state for multiple workspaces from an onprem TF4B to TFCB and did automate it around tf-helper (https://github.com/hashicorp-community/tf-helper). I know it's quite old but totally perfect for such usecases.

We created and manage the new workspaces in TFCB with Terraform. Then we had a bash script locking the new and old workspace, exporting state, importing it, do some VCS config, unlock the new workspace,...
All idempotent to run it multiple times during migration if needed. We never used it afterwarda anymore cause the job was done.

Just my 2 cents, this also refers and applies to https://github.com/hashicorp/terraform-provider-tfe/issues/251

**Comment by Sreerag74031** [comment]
@jgrumboe I agree the state file migartion is one time for each workspace. 
We have 500+ state files to be migrated and this new resource would really help.
We like the tfe resource based solution so we can do everything as Terraform IaC (we love it).

**Comment by jgrumboe** [comment]
I also love IaC 😄 
I'm still not convinced how this resource would help you after migration...a resource would always try to recreate the state defined, which in this case would mean that after migration and doing your first TF applies in the new workspace the resource would recognize a "drift" to the original GCS state file and would try to reapply/migrate the state again, wouldn't it?

So you would need to create a lifecycle stanza or remove it from your code. But if you remove it there's the next problem, it would try to remove the state version, because that's the normal behavior of a tf resource and that would be a problem I think.

Sorry, if I probably make it complicated.

**Comment by Sreerag74031** [comment]
Now i agree to you completely. a resource may not work. A state version option in workspace resource may help. We could use a flag to control when to do the migration. For this to work workspace resource need locking feature too.

**Comment by jgrumboe** [comment]
Yeah, the locking feature would be cool anyway.

**Comment by Sreerag74031** [comment]
Closing this request,a new request #361  opened for state version option in workspace resource.
