### ISSUE TITLE
Why "tag_names", not "tags"?

### ISSUE THREAD

**Issue by robinbowes** [hashicorp/terraform-provider-tfe#363]
#### Use-cases

We've been using TFC (was TFE) for > three years, and one of the first support tickets I raised was to request some better way of organising workspaces (Nov 2018!).

Here we are, nearly 3 years later and I see an announcement that you have finally implemented tags for Workspaces. Huzzah🎉 🍾

However, on further investigation, I am disappointed to learn that you have not implemented tags, just tag keys/names.

I invite you to look at how other cloud providers do this:

AWS: https://docs.aws.amazon.com/general/latest/gr/aws_tagging.html
> Each tag has two parts:
>
> A tag key (for example, CostCenter, Environment, or Project). Tag keys are case sensitive.
> 
> A tag value (for example, 111122223333 or Production). Like tag keys, tag values are case sensitive.

GCP: https://cloudplatform.googleblog.com/2015/10/using-labels-to-organize-Google-Cloud-Platform-resources.html
> A label is a key:value pair that can be attached to a project or a VM

Azure: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-resources
> Each tag consists of a name and a value pair. For example, you can apply the name Environment and the value Production to all the resources in production.

Why have you done it this way, and not taken the common approach used by many other providers?

#### Attempted Solutions

I guess we'll have to create tag names containing the value as well, eg `stage:production`, etc.

#### Proposal

I'd like to propose that you implement tags as key/value pairs, as done by many other cloud providers.

**Comment by vaficionado** [comment]
Hi there @robinbowes and thanks for the note! I'm the product manager for the workspace tagging project we recently shipped, and I wanted to pop in and give you some context on why we made the decision we did here. 

We on the project team spent weeks researching this exact question; whether "tags" should be key:value pairs or singletons, what the accepted industry definition of a "tag" vs a "label" was, and what kind of mental model our users wanted to apply to managing Terraform workspaces. One of the two things we learned for certain were that there's no consistent use of "tags" vs "labels" as a concept in the industry. And the second is that no matter which way we went - there would be some folks who definitely wanted the other!

That being said, a pattern started to emerge that the majority the users we spoke with see the Terraform platform as more similar to other information management tools than to the hyperscaler clouds themselves. These tools are more like (for example) Jira, Confluence, Gmail, Asana, etc. These tools implement singleton tags/labels that are more about grouping and managing metadata, and the pattern applied more cleanly to the Terraform Cloud workflows we wanted to enable. 

However, you hit our conceptual workaround exactly - both the UI and API are built to allow you to use a separator character in your tag, so you can enter tags as `key:value` and parse them via the API or an external tool with minimal effort. 

The whole team and I definitely appreciate and welcome your feedback on this 😄  However, in this case, since the `tfe` provider is just implementing what the platform exposes, I'd ask that you log this request through the Terraform Cloud support process so we can properly track it there. Feel free to reference this issue/comment/etc when you do so. 

Thanks so much for using Terraform!

**Comment by robinbowes** [comment]
Hi Jon,

Thanks for the reply. It is pretty much as I expected.

I think the primary issue here is that you've implemented labels and called them tags :)

I also realised after submitting this issue that this is not really a provider issue, but more deeply embedded in the whole ecosystem so have raised the issue through our support channel so I'll close this for now. 

Many thanks,

R.
