### ISSUE TITLE
Data source tfe_output 

### ISSUE THREAD

**Issue by nikolaifa** [hashicorp/terraform-provider-tfe#373]
#### Use-cases
I want to retrieve outputs in one workspace from two different workspaces. Each outputs a map named `appRoles`. I want to iterate over this map using `for_each`. 

#### Attempted Solutions

- This would be possible with the data source `tfe_outputs` if it didn't statically mark the values as sensitive
- I can probably use the `terraform_remote_state `data source which is built in, but I figure a native data source for Terraform Cloud is a cleaner solution

#### Proposal

Create a new data source which retrieves a specific output from a specific workspace.

I suggest `tfe_output` with the arguments
- organization
- workspace
- name

Thanks for your time 😄

**Comment by chrisarcand** [comment]
Hi!

[The values are marked as sensitive because they may be considered sensitive in the context of the sourced workspace.](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/data-sources/outputs) The value used in `for_each` is used to identify the resource instance and will always be disclosed in UI output, which is why sensitive values are not allowed. 

See [the documentation on the limitations of `for_each`](https://www.terraform.io/docs/language/meta-arguments/for_each.html#limitations-on-values-used-in-for_each), as using a `for` is often a better solution if you just need the keys.

---

That being said, you should be able to achieve exactly what you're after without a specialized data source in this provider; use `nonsensitive()` function on the `values` map of the `tfe_outputs` datasource and it will behave as you expected.

**Comment by nikolaifa** [comment]
Thanks, I wasn't aware of the function `nonsensitive()`, it solves my issue.
