### ISSUE TITLE
possible memory leak introduced in 0.27.0

### ISSUE THREAD

**Issue by devopsrick** [hashicorp/terraform-provider-tfe#407]
We are seeing an unstable spike in memory utilization with 0.27.0 release during workspace plans.  It does not happen in the previous release(s).  I will open a support case as well but wanted to mention here.

**Comment by brandonc** [comment]
Thank you for raising this issue when you noticed it. Scanning through the released changes, nothing in particular jumps out at me. Can you relate additional details, such as whether you have many of any particular resource defined in your config? Or your methodology for discovering the leak?

**Comment by devopsrick** [comment]
The memory leak (perhaps not the right term, greatly increased memory usage) manifested as brief UI downtime during any plan for my tfe provider workspace.  As the provider had just updated I pinned it back to confirm if that was causing it, and verified in the replicated admin UI that the memory usage was spiking very strangely during plans vs the pinned provider plans.

At first glance it appears the run is spending significantly more time traversing relationships/remote-state-consumers

**Comment by devopsrick** [comment]
I am only able to get a partial run log when I enable TRACE logging with 0.27.0 but it seems to support this being the issue.

➜  grep "relationships/remote-state-consumers" run-0.26.1-plan-log.txt|wc -l
    5711
➜  grep "relationships/remote-state-consumers" run-0.27.0-partial-plan-log.txt|wc -l
   29930

**Comment by devopsrick** [comment]
Here is a high level breakdown of my resources.  Perhaps it is the workspace data sources?

>  173 data.tfe_workspace.all
>     2 data.tfe_workspace_ids
>    1 tfe_agent_pool
>    1 tfe_agent_token
>   77 tfe_notification_configuration
>    1 tfe_organization
>   10 tfe_policy_set
>    2 tfe_policy_set_parameter
>   90 tfe_registry_module
>    1 tfe_run_trigger
>   22 tfe_team
>  429 tfe_team_access
>    1 tfe_team_token
>  891 tfe_variable
>  173 tfe_workspace

**Comment by brandonc** [comment]
Thanks for the additional insight. I can look more at the performance of up to two pages of state consumers for < 200 workspaces. Out of curiosity, does your config suffer from the bug described in #367? --

> Previously, any number of remote state consumers over a standard page (20 results) would cause a subsequent plan to try and continue adding the list of consumer IDs indefinitely, as the Read implementation didn't take pagination in to account.

When you say that your workspaces have remote states open to "any other workspace" do you mean all other workspaces? In that case, you could use the `global-remote-state` workspace option as [described here](https://www.terraform.io/cloud-docs/api-docs/workspaces#request-body) otherwise, maybe you can characterize how many workspaces are listed in remote state consumers?

**Comment by devopsrick** [comment]
Oh yes I just mean they are all globally accessible, not that we specify every other workspace as an allowed consumer.   I think we explicitly lock down maybe 4 or 5 workspace states to be readable by each other in total.

I am not aware of us experiencing that pagination bug, but I don't think I have tried to use the remote state consumer part of the workspace data source at all yet.  We mostly use them to create an output with workspace backing repo and terraform version data that we use elsewhere.

**Comment by brandonc** [comment]
@devopsrick The problem is not a memory leak, but a bug in our workspace data source that [populates all workspace remote_state_consumer_ids even global remote state is true](https://github.com/hashicorp/terraform-provider-tfe/blob/main/tfe/data_source_workspace.go#L171) and also mishandles global_remote_state. The [workspace resource doesn't suffer from this](https://github.com/hashicorp/terraform-provider-tfe/blob/main/tfe/resource_tfe_workspace.go#L377-L388). Thanks for your help in diagnosing this- I should be able to get a fix released today.

**Comment by brandonc** [comment]
This was released as 0.27.1
