### ISSUE TITLE
Add Existing Varset to Workspace

### ISSUE THREAD

**Issue by jacobtaunton** [hashicorp/terraform-provider-tfe#467]
#### Use-cases
When there is existing varset
Then be able to add it to new workspace in IaC

#### Attempted Solutions

resource "tfe_variable_set" "this" {
name = var.varset
organization = var.organization
workspace_ids = [tfe_workspace.this.id]
}

│ Error: Error creating variable set 1234-varset, for organization: myorg: invalid attribute
│
│ Name has already been taken
│
│ with module.example.module.workspaces["test-tfc-demo-1234"].tfe_variable_set.this,
│ on ../modules/workspaces/main.tf line 43, in resource "tfe_variable_set" "this":
│ 43: resource "tfe_variable_set" "this" {

#### Proposal

Allow to attach existing varsets using tfe_variable_set.

data "tfe_variable_set" "test" {
  name         = "my-variable-set-name"
  organization = "my-org-name"
}

resource "tfe_variable_set" "this" {
  varset_id            = data.tfe_variable_set.test
  workspace_ids   = tfe_workspace.this.id
}

**Comment by claywd-rialtic** [comment]
@jacobtaunton I don't think this is a feature_request but rather a bug. the documentation says this is a supported feature already https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/variable_set

**Comment by claywd-rialtic** [comment]
Also currently running into this problem.
<img width="555" alt="Screen Shot 2022-03-31 at 8 26 26 PM" src="https://user-images.githubusercontent.com/99696743/161176835-41a47733-6de0-46f5-b1b3-7c85cc9ab1c7.png">

**Comment by claywd-rialtic** [comment]
Either the docs are out of date or the code needs to be updated but the docs call the argument `workspaces` and the code calls it `workspace_ids` https://github.com/hashicorp/terraform-provider-tfe/blob/main/tfe/resource_tfe_variable_set.go#L48

**Comment by jacobtaunton** [comment]
> Either the docs are out of date or the code needs to be updated but the docs call the argument `workspaces` and the code calls it `workspace_ids` https://github.com/hashicorp/terraform-provider-tfe/blob/main/tfe/resource_tfe_variable_set.go#L48
> 
> Ran into this with the resource `tfe_variable` as well when trying to set the `variable_sets` I had to use `variable_set_ids`

I commented on the PR to add varset, and was told there is a bug they are fixing. They called the value wonkspace.

**Comment by jacobtaunton** [comment]
Unfortunately I'm still unable to add existing varsets to workspaces, or if I create a new varset in IaC I cannot add it to more than once workspace because I get an error that the resource already exists so it cannot be created.

How are we supposed to add existing varsets to workspace if we cannot use data to get varset id and use that to add to workspace?

resource "tfe_variable_set" "this" {
  name         = var.varset
  organization = var.organization
  workspace_ids   = [tfe_workspace.this.id]
}

│ Error: Error creating variable set 1234-varset, for organization: myorg: invalid attribute
│ 
│ Name has already been taken
│ 
│   with module.example.module.workspaces["test-tfc-demo-1111-svc1-main"].tfe_variable_set.this,
│   on ../modules/workspaces/main.tf line 43, in resource "tfe_variable_set" "this":
│   43: resource "tfe_variable_set" "this" {

**Comment by zahiar** [comment]
This is kind of related (if not, I'm happy to raise a separate issue 🙂 ) but it would be really useful to have like a linking resource, that will let you link an existing varset to a workspace (a one-to-one mapping).

Something like
```
data "tfe_workspace" "test" {
  name = "my-workspace-name"
  organization = "my-org-name"
}

data "tfe_variable_set" "test" {
  name = "my-variable-set-name"
  organization = "my-org-name"
}

resource "tfe_variable_set_link(?)" "test" {
  varset_id = data.tfe_variable_set.id
  workspace_id = data.tfe_workspace.id
  organization  = "my-org-name"
}
```

This is handy for the use-case where workspaces are provisioned using a module, and within that module you can pre-link var sets that aren't truly global and more akin to being an environmental varset. 

So imagine having a varset for a logging system like Graylog, you can create 3 varsets, one for each environment such as QA, Staging & Production, each containing provider-specific ENVs for each Graylog instance. Then each application's workspace would be linked to the appropriate Graylog Provider varset. 

For example,

|Workspace Name|Variable Set Name|
|-----------|-------|
|my-app-qa|Graylog Provider QA|
|my-app-stg|Graylog Provider Staging|
|my-app-prod|Graylog Provider Production|

**Comment by jacobtaunton** [comment]
> This is kind of related (if not, I'm happy to raise a separate issue 🙂 ) but it would be really useful to have like a linking resource, that will let you link an existing varset to a workspace (a one-to-one mapping).
> 
> Something like
> 
> ```
> data "tfe_workspace" "test" {
>   name = "my-workspace-name"
>   organization = "my-org-name"
> }
> 
> data "tfe_variable_set" "test" {
>   name = "my-variable-set-name"
>   organization = "my-org-name"
> }
> 
> resource "tfe_variable_set_link(?)" "test" {
>   varset_id = data.tfe_variable_set.id
>   workspace_id = data.tfe_workspace.id
>   organization  = "my-org-name"
> }
> ```
> 
> This is handy for the use-case where workspaces are provisioned using a module, and within that module you can pre-link var sets that aren't truly global and more akin to being an environmental varset.
> 
> So imagine having a varset for a logging system like Graylog, you can create 3 varsets, one for each environment such as QA, Staging & Production, each containing provider-specific ENVs for each Graylog instance. Then each application's workspace would be linked to the appropriate Graylog Provider varset.
> 
> For example,
> Workspace Name 	Variable Set Name
> my-app-qa 	Graylog Provider QA
> my-app-stg 	Graylog Provider Staging
> my-app-prod 	Graylog Provider Production

We're saying the same thing..
My plan was to create varsets using api, then do data to get the varset_id to add to a workspace id using the provider. This way I can add to for loop.
Now since this is not an option, I'm thinking create all varsets using IaC, and add all workspaces from tags.

**Comment by zahiar** [comment]
Hmm, you might be onto something there 💡 

We create all of our workspaces using a module, and we have like 500 workspaces so it's not like I can iterate through all of them since each workspace is an instantiation of a module (i.e. 500 module invocations in total).

But if I added tagging as you said, we could do something like this:
```
module "workspace-a"...
module "workspace-b"...
module "workspace-c"...
...

data "tfe_workspace_ids" "qa-apps" {
  tag_names    = ["qa"]
  organization = "my-org-name"
}

resource "tfe_variable_set" "provider-xxx" {
  name         = "XXX Provider"
  description  = "XXX Provider ENVs applied to all QA workspaces."
  global = false
  organization = data.tfe_organization.flashtalking.name
  workspace_ids = data.tfe_workspace_ids.qa-apps.ids
}

```

Or I could forgo tagging completely as our workspace names follow the convention of `<APP_NAME>-<ENVIRONMENT>` such as:
- my-app-qa
- my-other-app-stg
- yet-another-app-prod

So could get away with
```
data "tfe_workspace_ids" "qa-apps" {
  names    = ["-qa"]
  organization = "my-org-name"
}
```

I think this could work - tho' not tested the idea but still a good idea, thanks @jacobtaunton 👍

**Comment by claywd-rialtic** [comment]
@jacobtaunton why not just define the var_sets as resources and import them then provide the workspaces you want to attach them too as a list in the resource?

**Comment by jacobtaunton** [comment]
> @jacobtaunton why not just define the var_sets as resources and import them then provide the workspaces you want to attach them too as a list in the resource?

There was going to be code using the api to create the varsets, so the list of varsets would be changing. We are using terraform cloud, so not really clear on how of if this would work in IaC. The way the provider is today I will need to create varsets using terraform, and best way I see to add the workspaces is tagging.

**Comment by jacobtaunton** [comment]
> 

I tested this out and working good so far. I have a module to create the workspaces, then a a new module for the varsets. The varsets module depends on workspaces module. This is what's in the varset module.
# Get the workspaces that have varset tags.

data "tfe_workspace_ids" "this" {
  tag_names    = [var.varset_name]
  organization = var.organization
}

# Add the workspaces based on the tags.
resource "tfe_variable_set" "this" {
  name          = var.varset_name
  description   = "Variable set applied to workspaces based on tag."
  organization  = var.organization
  workspace_ids = values(data.tfe_workspace_ids.this.ids)
}

**Comment by Satak** [comment]
I also need to add existing variable sets to workspaces and this is clearly the best proposal:

```hcl
resource "tfe_variable_set_link" "variable_set_link" {
  variable_set_id = data.tfe_variable_set.set.id
  workspace_id    = data.tfe_workspace.ws.id
  organization    = local.organization
}
```

or add new parameter `variable_set_ids ` to `tfe_workspace` resource:

```hcl
resource "tfe_workspace" "test" {
  name             = "my-workspace-name"
  organization     = local.organization
  variable_set_ids = [data.tfe_variable_set.set.id]
}
```

**Comment by claywd-rialtic** [comment]
@Satak @jacobtaunton how shall we handle the race condition that occurs when one resource specifies a link and the other does not. What if they both specifiy links but to other resources. ie. 

workspace B mentions nothing about varset A
varset A  says link to workspace B
workspace A says link to varset A

since no mention of varset A occurs in workspace B the link gets created in one run and removed in the next because each resource is only satisfied when the other is drifted. 

likewise, workspace A tries to apply varset A to its workspace but since varset A doesn't mention workspace A and instead mentions workspace B there is another race condition. 

Technically these are less race conditions and more state machine logic failure but you catch my drift. The workflow you propose likely needs to be a whole solution. I think its likely fine to have two different workflows that are incompatible but we gotta spell all that out before someone really considers implementing this.

**Comment by jacobtaunton** [comment]
@claywd-rialtic why not treat linking varsets to workspaces same as applying teams access with tfe_team_access? This pattern works well, and I think the same would work good for varsets, policy_sets, and run tasks. As long as the resource exists do data query to get the id and link to workspace_id.

**Comment by cuotos** [comment]
In agreement with many of then comments above, a `tfe_variable_set_attachment` resource would be handy.

My use case is to create a small number variable sets, these are long lived.

Workspaces are created afterwards and will need to have a var set added to them at creation time, but it would be nice for the workspace and varset-workspace relationship to be separate operations.

I'm thinking along the lines of AWS IAM Policy / Roles / Attachements...

```
resource "tfe_workspace" "ws1" {}

resource "tfe_variable_set" "vs1" {}

resource "tfe_variable_set_attachment" "attach" {
  workspace_id = tfe_workspace.ws1.id
  variable_set_id = tfe_variable_set.vs1.id
}
```

**Comment by sebasslash** [comment]
So let me see if I understood the issue correctly as I have a potential workaround (although it's not v pretty and can get complicated with more complex configurations).

I want to take a variable set, `varsetA`, that exists outside my configuration/state and be able to add it to workspaces that I create within my configuration? If so here's a way to do it:

Lets start off with our configuration: `main.tf`. It should look like so (We'll omit the provider configuration) 
```hcl
resource "tfe_variable_set" "varsetA" {}
```
Then, we'll want to import the resource `terraform import tfe_variable_set.varsetA varset-XXXXXXXX` (substitute your desired variable set ID) 

Cool! Import is successful, now I want to be able to use this resource. I'll run a quick `terraform plan` to check for any errors. Behold! Missing `name` and `organization`! No bueno, so we'll want a way to get the name and organization as well as the rest of the attributes for this variable set. We'll use a **data source** for this. 

Now my configuration will look like so:
```hcl
data "tfe_variable_set" "fetched" {
  name = "varsetA"
  organization = "star-destroyers"
}

resource "tfe_variable_set" "varsetA" {
  name = data.tfe_variable_set.fetched.name
  organization = data.tfe_variable_set.fetched.organization
}
```

Run a quick `terraform plan` and everything should be A-OK 👍 . Now for the part we want, adding workspaces we create through Terraform. First let's create the workspace:
```hcl
resource "tfe_workspace" "test" {
  name = "tie-fighters"
  organization = "star-destroyers"
}

data "tfe_variable_set" "fetched" {
  name = "varsetA"
  organization = "star-destroyers"
}

resource "tfe_variable_set" "varsetA" {
  name = data.tfe_variable_set.fetched.name
  organization = data.tfe_variable_set.fetched.organization
}
```
Run `terraform apply` and it should succeed. Now to add that new workspace we'll use the `setunion()` method  (since `workspace_ids` is a set) to append to the existing workspaces returned from the data source:
```hcl
# omitting the varset data source and workspace resource for brevity
resource "tfe_variable_set" "varsetA" {
  name = data.tfe_variable_set.fetched.name
  organization = data.tfe_variable_set.fetched.organization
  workspace_ids = setunion(data.tfe_variable_set.fetched.workspace_ids, toset([tfe_workspace.test.id]))
}
```
Run `terraform apply` and voila! I have added the `tie-fighters` workspace to an existing variable set 🚀 If you have a list of workspace that's a variable, simply replace the value in `toset()` to `toset(var.my_workspace_ids)` 

Let me know if this solves your issue! 💜

**Comment by cuotos** [comment]
unfortunately I don't think that work for me. (or without some potentially nasty confusing data calls etc)

For context I have a tf file, that my developers can add a module block to and it will bootstrap TFCloud workspaces, git repos,  cloud infra (multiple environments) related to the service they want to build. I'd like that initialisation to be as simple as possible, at the moment its a case of adding one block.

```
module "new_service" {
  source       = "./module"
  service_name = "new_service"
  ... a small number of other options
}
```

Ideally that is ALL they would need to add, but using the var_set system currently in place, they would also need to add to a list in the var_set object, ( and I would want to avoid creating modules from a for_each due to the other options that might be required)

```
resource "tfe_variable_set" "test" {
  name          = "Varset"

  workspace_ids = flatten([
      # the module creates a number of workspaces, depending on some other input criteria.
      module.new_service.workspace_ids,
      module.another_service.workspace_ids,
    ])
}
```

This would require 2 places to update when creating a new service. When it would be much easier if the sub module could just add an existing varset to the workspace at creation time (either by passing the var_sets id in the workspace resource, or better, linking them using an new resource "varset_attachment" type thing...). 

While it is do-able, it doesn't feel very idiomatic.

I hope this explains my use case...

**Comment by sebasslash** [comment]
This clarifies quite a bit, thank you! I misread the desired behavior here so I apologize! Given your use case, perhaps the best strategy indeed will be to introduce a separate resource to manage these relationships -- as people have previously mentioned. We'll have some internal discussions on how best to approach this given that this relationship can also perhaps be modeled through the API instead, simplifying the logic on the provider's end. 

Big thank you to all :)

**Comment by claywd-rialtic** [comment]
> @claywd-rialtic why not treat linking varsets to workspaces same as applying teams access with tfe_team_access? This pattern works well, and I think the same would work good for varsets, policy_sets, and run tasks. As long as the resource exists do data query to get the id and link to workspace_id.

I'm down for it. @sebasslash open to prs for this?

**Comment by filippo-20tab** [comment]
I would be extremely interested in a linking resource too, I am kind of stuck at the moment. Thanks a lot!

**Comment by jacobtaunton** [comment]
> I would be extremely interested in a linking resource too, I am kind of stuck at the moment. Thanks a lot!

I went back to using API. Get varset_id with data then use local-exec python to attach varset. This is working good for me, hope it helps.

`  provisioner "local-exec" {
    command = "python3 ${path.module}/add_varset.py -w ${tfe_workspace.this.id} -v ${data.tfe_variable_set.this.id} -t ${var.tfe_token}"
  }`


`import argparse
import requests

########################################################################################
#Default values can be changed to your specific key, or you can pass them in CLI.
parser = argparse.ArgumentParser()
parser.add_argument('-t', '--token', help="tfe token", default=None)
parser.add_argument('-w', '--workspace', help="workspace id", default=None)
parser.add_argument('-v', '--varset', help="varset name", default=None)
args = parser.parse_args()
########################################################################################

def add_varset_to_workspace(api_headers, varset_id, workspace_id):
  """Makes API Call to TFC to add varset ID to workspace ID"""
  url = 'https://app.terraform.io/api/v2/varsets/' + varset_id + '/relationships/workspaces'
  post_data = '{ "data": [ { "type": "workspaces", "id": "'+ workspace_id +'" } ] }'
  response = requests.post(url, headers=api_headers,  data=post_data)
  print(response)
  print(response.text)

def main():
  """Gets the args needed to add the varset to the workspace"""
  token = args.token
  api_headers= {'content-type': 'application/vnd.api+json', "Authorization": "Bearer " + token}
  varset_id = args.varset # comes from argparse -v
  workspace_id = args.workspace # comes from argparse -w
  add_varset_to_workspace(api_headers, varset_id, workspace_id)

#Code starts here
if __name__ == "__main__":
  main()`

**Comment by sebasslash** [comment]
Hi @claywd-rialtic I apologize for keeping you waiting 😞 ! We're going to hold off on a provider implementation (for now). I spoke with the team behind variable sets and it could very well be the relationship: `varset => workspace` could actually be expressed as an API resource. An example of this idea would be the [Team Access API](https://www.terraform.io/cloud-docs/api-docs/team-access)

In which case it will drastically simplify the logic for handling this with the provider. No concrete answer as of yet, but I'll make sure to notify you should we choose to move forward with a provider implementation. You'll get first cut at the cake :)

**Comment by dkirrane** [comment]
+1 
For consistency it could probably work like `tfe_run_trigger` e.g.

```
data "tfe_variable_set_ids" "this" {
  names           = toset("var set 1", "var set 2")
  organization = var.organization
}

resource "tfe_variable_set_link" "this" {
  for_each = data.tfe_variable_set_ids.this.ids

  workspace_id   = tfe_workspace.this.id
  variable_set_id = each.value
}
```

**Comment by drewmullen** [comment]
I opened a PR to add this feature. works great locally. Please 👍 to expedite getting it merged

https://github.com/hashicorp/terraform-provider-tfe/pull/526
