### ISSUE TITLE
Provider didn't detect a change in config

### ISSUE THREAD

**Issue by ausfestivus** [hashicorp/terraform-provider-tfe#511]
#### Terraform Cloud/Enterprise version

Terraform Cloud

#### Terraform version
```plaintext
Terraform v1.2.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/tfe v0.31.0
+ provider registry.terraform.io/hashicorp/vault v3.6.0
```

#### Terraform Configuration Files
When the `plan` and `apply` was first run in the TFC Workspace we had this config

```terraform
variable "tfc_token" {
  type      = string
  sensitive = true
}

provider "tfe" {
  token = var.token
}
```
And that worked.

Later on, we switched over to this config

```terraform
provider "tfe" {
  token = vault_terraform_cloud_secret_creds.tfc.token
}

resource "vault_terraform_cloud_secret_creds" "tfc" {
  backend = local.vault_tfc_token[var.environment].backend
  role    = local.vault_tfc_token[var.environment].role
}

locals {
  vault_tfc_token = {
    dev = {
      backend = "acl_cpt/tfc_dev"
      role    = "tfc-orgname-dev-org-token"
    }
    prod = {
      backend = "acl_cpt/tfc_prod"
      role    = "tfc-orgname-prod-org-token"
    }
  }
}
```

And it worked fine as well.

Later on, I deleted the Workspace and recreated it with the newer (2nd) config above that uses the Vault integration. The first `plan` and `apply` in the new Workspace failed.

#### Debug Output
The most relevant content I could find from debug output was

```plaintext
2022-06-03T02:04:53.078Z [INFO]  ReferenceTransformer: reference not found: "local.vault_tfc_token"
2022-06-03T02:04:53.078Z [INFO]  ReferenceTransformer: reference not found: "local.vault_tfc_token"
```

#### Expected Behavior

TFE Provider should have detected the config change and used it.

#### Actual Behavior

The error below was output in the first `plan` and `apply` in a new Workspace.

`terraform plan` fails with

```plaintext
Error: Error retrieving provider meta values for internal provider.
│ 
│   with provider["registry.terraform.io/hashicorp/tfe"],
│   on main.tf line 43, in provider "tfe":
│   43: provider "tfe" {
│ 
│ This should never happen; please report it to
│ https://github.com/hashicorp/terraform-provider-tfe/issues
│ 
│ The error received was: "Could not set the token value to string
│ unmarshaling unknown values is not supported"
╵
Operation failed: failed running terraform plan (exit 1)
```

#### Additional Context

https://github.com/hashicorp/terraform-provider-vault/issues/1178

**Comment by annawinkler** [comment]
Thank you for submitting this issue. We're looking into what you've described.

**Comment by annawinkler** [comment]
Hi @ausfestivus - thank you for submitting this issue, [this](https://github.com/hashicorp/terraform-provider-tfe/issues/512) related one, and [this](https://github.com/hashicorp/terraform-provider-vault/issues/1178) vault provider issue.

After looking at what you've described, you are correct - the plan requires information that is not known until an apply. This is how things work currently - the values would not be known until the apply happens. So, the workaround you've described in the vault provider issue is one approach, and another alternative could be to use multiple terraform execution pipelines that pass the outputs of one to another.

I'm going to close this issue because currently we do not have plans to change this behavior.
