### ISSUE TITLE
Provider documentation for tfe_variable_set provides an example that doesn't work.

### ISSUE THREAD

**Issue by jplanza-gr** [hashicorp/terraform-provider-tfe#559]
#### Terraform Cloud/Enterprise version

Terraform Cloud

#### Terraform version

```plaintext
Terraform v1.2.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/tfe v0.33.0
```

#### Terraform Configuration Files

```terraform
resource "tfe_workspace_variable_set" "test" {
  for_each        = toset(values(data.tfe_workspace_ids.prod-apps.ids))
  workspace_id    = each.key
  variable_set_id = tfe_variable_set.test.id
}
```

#### Debug Output

```plaintext
│ Error: Invalid for_each argument
│ 
│   on test.tf line 13, in resource "tfe_workspace_variable_set" "test":
│   13:   for_each        = toset(values(data.tfe_workspace_ids.prod-apps.ids))
│     ├────────────────
│     │ data.tfe_workspace_ids.prod-apps.ids is a map of string, known only after apply
│ 
│ The "for_each" set includes values derived from resource attributes that
│ cannot be determined until apply, and so Terraform cannot determine the
│ full set of keys that will identify the instances of this resource.
│ 
│ When working with unknown values in for_each, it's better to use a map
│ value where the keys are defined statically in your configuration and where
│ only the values contain apply-time results.
│ 
│ Alternatively, you could use the -target planning option to first apply
│ only the resources that the for_each value depends on, and then apply a
│ second time to fully converge.
```

#### Expected Behavior

Provider documentation should include working examples:

https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/variable_set

#### Actual Behavior

The for_each example works during the initial apply, but subsequent applies produce the error above.

#### Additional Context

Using the data resource and a for_each seemed like a clean way to do this, but it clearly doesn't work.  If the language isn't going to support this pattern, please don't use it in the official provider documentation.

**Comment by annawinkler** [comment]
Thank you for submitting this issue! We've verified that the example is incorrect and we'll be removing the example.

After we thought about it, managing variable sets via tags isn't that desirable because users who may not have the security access could then gain access via a tag, bypassing security.

If you really do want to bypass the security model of variable set attachment, you would need to create two separate Terraform configs.
The first config would create the organization & workspaces, and the second config would then add the variable sets to the workspaces.
