### ISSUE TITLE
Problem with credentials_helper

### ISSUE THREAD

**Issue by chris3ware** [hashicorp/terraform-provider-tfe#637]
#### Terraform version

```plaintext
Terraform v1.3.0
on darwin_amd64
```

#### Terraform Configuration Files

```zsh
➜ ~ lsa ~/.terraform.d/plugins

Permissions Size User  Date Modified Name
.rwxr-xr-x  8.6M chris 28 Sep 12:18  terraform-credentials-keychain


➜ ~ cat ~/.terraformrc

credentials_helper "keychain" {
  args = ["--keychain=terraform"]
}
```

```terraform
provider "tfe" {
}

terraform {
  required_version = ">= 1.3.0"
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 5.2.0"
    }

    tfe = {
      version = "~> 0.36.1"
    }
    sops = {
      source  = "carlpett/sops"
      version = "~> 0.7.1"
    }
  }

  backend "remote" {
    organization = "3ware"
    workspaces {
      name = "3ware-repoman"
    }
  }
}

resource "tfe_organization" "threeware" {
  name  = "3ware"
  email = "<EMAIL>"
}

resource "tfe_workspace" "this" {
  for_each          = { for workspace in var.workspaces : workspace.name => workspace }
  name              = each.value.name
  organization      = tfe_organization.threeware.name
  description       = each.value.description
  working_directory = try(each.value.working_directory, "terraform")
  execution_mode    = try(each.value.execution_mode, "local")
  vcs_repo {
    identifier     = "${tfe_organization.threeware.name}/${each.value.repo}"
    oauth_token_id = data.sops_file.token.data["oauth_token_id"]
  }
}
```

#### Debug Output

```plaintext
https://gist.github.com/chris3ware/2a471834152440ad2aa59e85773aea5a
```

#### Expected Behavior

TFE provider should retrieve the terraform cloud API key from masOS key chain using the credentials_helper configuration in ~/.terraformrc to refresh state of terraform cloud resources.

#### Actual Behavior

Terraform plan fails because it is unable to refresh the state of the terraform cloud resources.

#### Additional Context

I am using terraform cloud for remote state workspaces in local execution mode.

I also raised an issue on the credentials_helper repo: bendrucker/terraform-credentials-keychain#38. 

The provider works as expected when the terraform cloud api token is configured in the provider configuration, as an environment variable or as credentials in ~/.terraformrc.

**Comment by sebasslash** [comment]
Hi Chris! :wave: 

Thank you for submitting this issue. One caveat I'd like to clear up here is that credential helpers authenticate Terraform, not providers (which are the ones making API requests to refresh specific resources in state). So what your credential helper actually does is authenticate you for Terraform specific network operations like fetching a module from a registry or authenticating with a specific backend. 

One more intrinsic problem with your request is that you are using `backend "remote"` which means your plan is executing on a remote machine -- so even if we were to add support in the provider to use `terraform-credentials-keychain` for authentication, the remote VMs running Terraform for you won't have access to your keychain. 

Some more bad news: since v1.2 of Terraform the env credential helper is now built-in and the TFE provider in v0.31 piggy backed off this feature. However it was subsequently removed in v0.32 because it failed to work properly in a remote execution context. 

I hope this clears up some of the confusion here (and hopefully helps you!). I will close this ticket later this week if you don't have any more concerns or objections. Thanks again :purple_heart:

**Comment by sebasslash** [comment]
Oh! I just noticed you mentioned you are using local execution mode, apologies! The original distinction of Terraform auth vs Terraform provider auth still holds, unfortunately.

**Comment by chris3ware** [comment]
Ah, OK, thanks for the info. That does make sense.
