### ISSUE TITLE
Why is Config referred to as a pointer?

### ISSUE THREAD

**Issue by preslavrachev** [hashicorp/terraform-provider-tfe#790]
I am sorry for the seemingly dumb question but why is the `Config` struct referred to as a pointer? 

https://github.com/hashicorp/terraform-provider-tfe/blob/82c02b22d88d4f5f93ac44b74fb2c826981bc46c/tfe/provider.go#L360

From my point of view, it contains nothing that really requires a pointer semantic. Indeed, the two maps it holds reference to are pointers themselves, but still, it would have been the same effect if you'd just copied a `Config` value around. As it is, you always need to guarantee it's non-nillability.

**Comment by brandonc** [comment]
I don't think there is a good reason for this for the same reasons you pointed out, but I also see this as a style issue and not an API issue since this provider does not expose this private function in any way. The function never returns nil and nil is never checked and therefore this could easily be restructured to use and return value types. I got curious about it and see that it goes back to the very first commits to the repo and probably hasn't been touched since.
