### ISSUE TITLE
global argument for tfe_organization_run_task

### ISSUE THREAD

**Issue by starlightromero** [hashicorp/terraform-provider-tfe#866]
#### Use-cases

Goal - I want to add a run task to every workspace in an organization using the minimum amount of resources.

#### Attempted Solutions

The current solution for adding a run task to every workspace is to first create a `tfe_organization_run_task`, which creates the run tasks. Then assign the run task to every workspace using `tfe_workspace_run_task`.

This means there is a linear relationship between the number of workspace resources and the number of run task resources.

#### Proposal

I propose that either `tfe_organization_run_task` or a new run task resource uses the `global` argument. Similar to global policy sets with `tfe_policy_set`.

**Comment by brandonc** [comment]
@starlightromero thanks for the feature request. The `global` argument is actually supported by the platform with respect to policy sets but not run tasks. There is a subtle difference on the platform between the two, because policy sets have an organization level enforcement mechanism, while run tasks are more about third party integrations that a workspace can choose from (like a catalog, I guess?).

In the past, we've used mechanisms like a single `workspace_ids` argument on a resource that can be assigned to multiple workspaces, but we've nearly always needed to go back and offer a more flexible 'edge' resource like `tfe_workspace_run_task`. (See `tfe_team_organization_member`, `tfe_workspace_variable_set`, `tfe_workspace_policy_set`, and `tfe_project_variable_set`) In the case of run tasks, we went straight for the edge resource because the two cannot co-exist in the same config and we must always disclaim that.

I can think of two simplifications for your config to reduce the amount of resources you have to author: 1) Use a meta argument like for_each to define the run tasks for the workspaces, or 2) encapsulate the always-repeated resources using a module that defines a workspace and its run tasks.
