### ISSUE TITLE
tfe_organization_teams data lookup to return list of teams in a given organization

### ISSUE THREAD

**Issue by astanfel** [hashicorp/terraform-provider-tfe#913]
#### Use-cases
I would like to request a new feature that enables the retrieval of a list of all teams within a specific organization in Terraform Cloud/Enterprise. This feature would be beneficial in the following use-cases:

1. Auditing and Compliance: Users may need to generate reports or perform audits to ensure proper access control and governance within the organization. Having the ability to retrieve a list of teams would greatly assist in this process.

1. Automation and Integration: Users may want to integrate Terraform Cloud/Enterprise with other systems or build automation workflows. Being able to programmatically retrieve the list of teams would allow for more seamless integration and automation.

1. User Input Validation: When configuring infrastructure with Terraform, it's important to validate user input to ensure that the specified team exists within the organization. This feature would enable validation of team names provided by users during infrastructure provisioning, preventing the creation of resources with non-existent or misspelled team names.

#### Attempted Solutions
I have attempted to address this requirement by utilizing the existing `tfe-provider` for Terraform. However, the current provider does not provide a direct way to retrieve a list of teams in an organization.

#### Proposal
I propose enhancing the `tfe-provider` to include a new data source or resource that allows users to retrieve a list of teams within a specific Terraform Cloud/Enterprise organization.

For example, the following configuration snippet demonstrates how the new feature might be utilized:

```hcl
data "tfe_organization_teams" "my_organization_teams" {
  organization = "my_organization"
}

output "teams" {
  value = data.tfe_organization_teams.my_organization_teams.names
}
```

This enhancement would introduce a new data source or resource named `tfe_organization_teams` that accepts the organization name as an input variable. It would return a list of team names within the specified organization. The example above showcases the usage of this new feature by capturing the team names within the organization and outputting them.

I believe that this proposed feature would greatly improve the usability and flexibility of the `tfe-provider`, empowering users to interact with and manage teams more effectively within Terraform Cloud/Enterprise.

Thank you for considering my feature request. I am open to further discussions and providing any additional information if needed.

Best regards,
Tony Stanfel

**Comment by isaac-collins** [comment]
@brandonc can I add a PR for a new data source 'tfe_organization_teams'?

**Comment by brandonc** [comment]
@isaac-collins I would absolutely welcome that and assist in validating/testing/whatever you need. I have a few suggestions for making it easy to adopt your change:

1. Many resources are owned by an organization since that is the topmost entity. Plus, the only way to list teams are [by organization](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/teams#list-teams). For that reason I would ask that you name your data source `tfe_teams`

2. Be sure to make your organization argument optional and use the organization from the provider config if none is given in the schema. There are lots of examples of this, but all of them use the provider sdk and not the more preferred provider framework... If you feel like an extra challenge, implement your data source in the [provider framework](https://github.com/hashicorp/terraform-provider-tfe/blob/main/tfe/provider_next.go#L113-L116) (similar to `tfe/data_source_saml_settings.go`) that was recently added to the provider.

Thanks for your assistance!

**Comment by isaacmcollins** [comment]
@brandonc see PR #992. Unfortunately, I'm having a hard time testing with my Free TFC account (I can't create more than 1 team) however, I was able to build and run the provider locally to retrieve the id/name of my single owners team. Please advise.

**Comment by astanfel** [comment]
@brandonc I see that this feature was added. When will the next release be out for the provider for us to use this data block?

**Comment by brandonc** [comment]
@astanfel we don't have a scheduled date, but historically we've been releasing every 2-4 weeks. Under normal circumstances, this should be released in the next 1-2 weeks. We have one other pending change to consider for release that we may want to collect. Overall, we try to strike a balance between incremental changes and upgrade maintenance burden.
