### ISSUE TITLE
Add variable sets as list to workspaces/projects

### ISSUE THREAD

**Issue by kaefferlein** [hashicorp/terraform-provider-tfe#915]
#### Use-cases

We are managing a huge number of workspaces/projects/variable sets.
Currently we are using the deprecated way of the `variable_set`: https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/variable_set#workspace_ids to attach a variable set to multiple workspaces.
=> only one resource is needed.

As this is deprecated we might need to use
- https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/workspace_variable_set
- https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/project_variable_set

Which would result in many more resources to create and refresh as I can not add a list there.

#### Attempted Solutions

nothing so far, sorry.

#### Proposal

I would really appreciate to be able to add multiple workspaces/projects like this:

```
resource "tfe_project" "test" {
  name         = "my-project-name"
  organization = "my-org"
}

resource "tfe_project" "test2" {
  name         = "my-project-name2"
  organization = "my-org"
}

resource "tfe_variable_set" "test" {
  name         = "Test Varset"
  organization = "my-org"
}

resource "tfe_project_variable_set" "test" {
  variable_set_id = tfe_variable_set.test.id
  project_id      = [tfe_project.test.id, tfe_project.test2.id]
}
```

same applies to the `workspace_variable_set` resource.
At least the API (https://developer.hashicorp.com/terraform/cloud-docs/api-docs/variable-sets#apply-variable-set-to-projects) says this is possible :)

**Comment by sebasslash** [comment]
Hi Anna! Thanks for submitting this issue (and apologies for taking a while to get back to you).  

We have normally tried to move away from "one-to-many" attributes, since they are slightly trickier to implement and can result in some unwanted behavior. For example, suppose the list of of project ids you provide has at least one ID that points to a now deleted project (maybe drift occurred). On our end we would have to make the decision to either ignore any invalid project IDs so the resource can apply successfully with the valid project IDs **OR** error and now the valid IDs don't get the intended variable set provisioned until the error is fixed. 

Therefore, what we've opted for is resources that establish a one-to-one relationship, so either the relationship is created or not at all, removing any ambiguity on how to handle invalid relationships and also allowing valid resources to be provisioned. Given you want to supply a list of project IDs anyways I would recommend using `for_each`:

```hcl
locals { 
  project_ids = ["proj-123", "proj-456", "proj-789"]
}

resource "tfe_project_variable_set" "test" {
  for_each = local.project_ids
  variable_set_id = tfe_variable_set.test.id
  project_id = each.value
}
```
 
 I'm still open to hearing alternative suggestions or rationale for why `for_each` isn't satisfactory for your use case. If resources under management (RUM) is a concern for you then that's a discussion to be had internally, so please let me know.

**Comment by barrettclark** [comment]
I'm closing this as stale. We can re-evaluate if we get more information.
